/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;


public class pantallaOpcionInvAnfi extends javax.swing.JFrame {

    public pantallaOpcionInvAnfi() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCrearpartida = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAnfiltrion1 = new javax.swing.JButton();
        btnInvitado1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        imgPatolli2 = new javax.swing.JLabel();
        imgPatolli = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla inicio");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PATOLLI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        btnCrearpartida.setBackground(new java.awt.Color(0, 153, 255));
        btnCrearpartida.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnCrearpartida.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearpartida.setText("Crear  Partida");
        btnCrearpartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearpartidaMouseClicked(evt);
            }
        });
        btnCrearpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearpartidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearpartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 140, -1));

        lblNombre.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblNombre.setText("Nombre ");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        btnAnfiltrion1.setBackground(new java.awt.Color(0, 153, 255));
        btnAnfiltrion1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnAnfiltrion1.setForeground(new java.awt.Color(255, 255, 255));
        btnAnfiltrion1.setText("Anfiltrión");
        btnAnfiltrion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnfiltrion1MouseClicked(evt);
            }
        });
        btnAnfiltrion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnfiltrion1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnfiltrion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, -1));

        btnInvitado1.setBackground(new java.awt.Color(0, 153, 255));
        btnInvitado1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnInvitado1.setForeground(new java.awt.Color(255, 255, 255));
        btnInvitado1.setText("Invitado");
        btnInvitado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInvitado1MouseClicked(evt);
            }
        });
        btnInvitado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitado1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInvitado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 120, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 190, -1));

        imgPatolli2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1patolli.png"))); // NOI18N
        jPanel1.add(imgPatolli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 90, 80));

        imgPatolli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1patolli.png"))); // NOI18N
        jPanel1.add(imgPatolli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoa.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearpartidaActionPerformed
      
    }//GEN-LAST:event_btnCrearpartidaActionPerformed

    private void btnAnfiltrion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnfiltrion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnfiltrion1ActionPerformed

    private void btnInvitado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInvitado1ActionPerformed

    private void btnAnfiltrion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnfiltrion1MouseClicked
        pantallaCrearPartida config = new pantallaCrearPartida();
        config.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnfiltrion1MouseClicked

    private void btnInvitado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvitado1MouseClicked
        pantallaCodigo codigo = new pantallaCodigo();
        codigo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInvitado1MouseClicked

    private void btnCrearpartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearpartidaMouseClicked
        pantallaTableroEspera tablero = new pantallaTableroEspera();
        tablero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearpartidaMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(pantallaOpcionInvAnfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(pantallaOpcionInvAnfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(pantallaOpcionInvAnfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(pantallaOpcionInvAnfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new pantallaOpcionInvAnfi().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAnfiltrion1;
    private javax.swing.JButton btnCrearpartida;
    private javax.swing.JButton btnInvitado1;
    private javax.swing.JLabel imgPatolli;
    private javax.swing.JLabel imgPatolli2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
